baseURL = "https://fashionmodel.me/"
title = "fashionmodel.me"
theme = "PaperMod"
enableRobotsTXT = true

[params]
  description = "FashionModel.me offers personalized email addresses with the exclusive fashionmodel.me domain. Stand out with a unique and stylish email address that reflects your passion for fashion and modeling. Secure your custom email today and make a statement with every message you send."
  keywords = ["fashion", "modeling", "personalized email"]  # SEO keywords
  author = "Me"
  defaultTheme = "auto"
  env = "production"

  social = [
    {name = "Twitter", url = "https://x.com/crizazemodels"},
    {name = "LinkedIn", url = "https://www.linkedin.com/company/crizazemodels/"}
  ]

[[menu.main]]
  identifier = "premium-emails"
  name = "Premium Email Addresses"
  url = "/premium/"
  weight = 1
