baseURL = "https://phpstack-1337489-4984604.cloudwaysapps.com/"
title = "fashionmodel.me"
theme = "PaperMod"
enableRobotsTXT = true

[params]
  description = "FashionModel.me offers personalized email addresses with the exclusive fashionmodel.me domain. Stand out with a unique and stylish email address that reflects your passion for fashion and modeling. Secure your custom email today and make a statement with every message you send."
  author = "Me"
  defaultTheme = "auto"

  social = [
    {name = "Twitter", url = "https://twitter.com/yourhandle"},
    {name = "LinkedIn", url = "https://linkedin.com/in/yourprofile"}
  ]

[[menu.main]]
  identifier = "premium-emails"
  name = "Premium Email Addresses"
  url = "/premium/"
  weight = 1

